name: Code check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install deps
        run: |
          python - m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run main.py
        run: |
          python main.py
